"""Placebo control-corpus generator (Task A2) for the dev-experience KB A/B.

`build_placebo` emits `groundloop/kb/data/placebo.toml`: one placebo skill per real KB skill in
`aaos_kb_seed.toml`. Each placebo copies the KB skill's `[skill.match]` VERBATIM (so it fires on
exactly the same cases) under `id = "placebo-" + <kb id>`, but replaces the guidance with
length-matched, deliberately IRRELEVANT filler that still carries the required
`Signature:`/`Localize:`/`Fix:` clauses (so it validates and is injected at both the localize and
fix stages).

It is the NULL arm of the KB A/B: any lift the real KB shows over this control isolates the guidance
CONTENT as the treatment, ruling out the confound of merely injecting *some* skill on those cases.
The output conforms to `groundloop/kb/validate.py` (closed-vocab predicate + owner-token leak red-test).
"""
from __future__ import annotations

from pathlib import Path

from groundloop.kb.validate import load_corpus

KB_SEED = str(Path(__file__).parent / "data" / "aaos_kb_seed.toml")
PLACEBO_SEED = str(Path(__file__).parent / "data" / "placebo.toml")

_HEADER = (
    "# Placebo control corpus — GENERATED by groundloop/kb/placebo.py; DO NOT EDIT BY HAND.\n"
    "# Each [[skill]] copies a groundloop/kb/data/aaos_kb_seed.toml skill's [skill.match] VERBATIM\n"
    "#   (id prefixed 'placebo-') so it fires on the identical cases, but its guidance is\n"
    "#   length-matched, deliberately IRRELEVANT filler. This is the null arm for the KB A/B: any\n"
    "#   lift the KB shows over it is attributable to guidance CONTENT, not to the mere act of\n"
    "#   injecting a skill on those cases. Conforms to groundloop/kb/validate.py.\n"
)

# Neutral, owner-token-free filler (verified leak-safe against FLEET_OWNER_TOKENS via validate_corpus).
_FILLER = (
    "This clause is placebo control text of matched length that conveys no diagnostic or "
    "corrective information and points at nothing in particular; it exists only so the treatment "
    "and control arms differ solely in the wording of the injected guidance, never in which cases "
    "the skill fires. "
)
_LABELS = ("Signature:", "Localize:", "Fix:")


def _toml_str(s: str) -> str:
    """Emit a TOML string. Prefer a literal (single-quoted) string so regex backslashes survive
    verbatim; fall back to an escaped basic string when the value contains a quote or a newline."""
    if "'" not in s and "\n" not in s:
        return "'" + s + "'"
    esc = s.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n")
    return '"' + esc + '"'


def _toml_array(vals) -> str:
    return "[" + ", ".join(_toml_str(str(v)) for v in vals) + "]"


def _placebo_guidance(reference: str) -> str:
    """Length-matched filler carrying the three required clauses; content is irrelevant."""
    target = max(len(reference), 120)
    overhead = sum(len(lab) + 2 for lab in _LABELS)
    per = max((target - overhead) // len(_LABELS), 40)

    def fill(n: int) -> str:
        reps = (n // len(_FILLER)) + 1
        return (_FILLER * reps)[:n].rstrip()

    return "\n".join(f"{lab} {fill(per)}" for lab in _LABELS)


def _render_skill(sid: str, provenance: str, guidance: str, match: dict) -> str:
    lines = [
        "[[skill]]",
        f"id = {_toml_str(sid)}",
        f"provenance = {_toml_str(provenance)}",
        "guidance = '''",
        guidance.strip("\n"),
        "'''",
        "",
        "[skill.match]",
    ]
    for key, vals in match.items():
        lines.append(f"{key} = {_toml_array(vals)}")
    return "\n".join(lines) + "\n"


def build_placebo(kb_path: str = KB_SEED, out_path: str = PLACEBO_SEED) -> int:
    """Generate the placebo corpus from `kb_path`, write it to `out_path`, return the skill count."""
    skills = load_corpus(kb_path)
    blocks = [_HEADER]
    for sk in skills:
        sid = sk["id"]
        provenance = (
            f"Placebo control paired to KB skill {sid}: length-matched, deliberately irrelevant "
            "guidance behind a verbatim-copied match predicate — fires on the identical cases while "
            "conveying no diagnostic content, isolating the KB guidance as the A/B treatment."
        )
        blocks.append(
            _render_skill("placebo-" + sid, provenance, _placebo_guidance(sk.get("guidance", "")),
                          sk.get("match", {}) or {})
        )
    Path(out_path).write_text("\n".join(blocks).rstrip() + "\n", encoding="utf-8")
    return len(skills)


if __name__ == "__main__":  # pragma: no cover
    print(build_placebo())
